### ISSUE TITLE
Migration phase 1 is failing on updating work item (links)

### ISSUE THREAD

**Issue by skeeler** [Microsoft/vsts-work-item-migrator#10]
After migration phase 1 creates the new work items, it attempts to link them and fails with a rather cryptic TF401349 error. Brief search on the TFS error code turned up very little of value. Here are the error lines from the log output:

```
[Error   @14.03.01.691] Exception during batch 1: TF401349: An unexpected error has occurred, please verify your request and try again.
[Error   @14.03.01.695] 25 total work item(s) failed.
[Error   @14.03.01.699]    25 work item(s) failed for this reason: CriticalError.
```
Here is the first batch request for updating the Task (280) to Requirement (290) work item child-parent linkage as output in the log file:

```
WIT BATCH REQUEST 1:

METHOD: PATCH
URI: /_apis/wit/workItems/282?bypassRules=True&suppressNotifications=True&api-version=3.0

BODY:
[{"op":1,"Path":"/relations/0","From":null,"Value":null},{"op":0,"Path":"/relations/-","From":null,"Value":{"rel":"AttachedFile","url":"http://hv-demo-tfs:8080/tfs/DefaultCollection/_apis/wit/attachments/9780e831-76c7-479f-bc99-f89dedde4366","attributes":{"name":"WorkItemHistory267.json"}}},{"op":0,"Path":"/fields/System.Tags","From":null,"Value":"20180303-1800"},{"op":0,"Path":"/relations/-","From":null,"Value":{"rel":"System.LinkTypes.Hierarchy-Reverse","url":"http://hv-demo-tfs:8080/tfs/DefaultCollection/_apis/wit/workItems/290","attributes":{"comment":""}}},{"op":0,"Path":"/relations/-","From":null,"Value":{"rel":"Hyperlink","url":"http://hv-demo-tfs:8080/tfs/DefaultCollection/_apis/wit/workItems/267","attributes":{"id":1018,"comment":"2;attachments;revision history attachments;target post move tags;work item links"}}}]

```
So I took the information above and fired it off in Postman, resulting in the following:

```
{
    "$id": "1",
    "innerException": null,
    "message": "TF401349: An unexpected error has occurred, please verify your request and try again.",
    "typeName": "Microsoft.TeamFoundation.WorkItemTracking.Web.Common.UnexpectedException, Microsoft.TeamFoundation.WorkItemTracking.Web",
    "typeKey": "UnexpectedException",
    "errorCode": 0,
    "eventId": 3000
}
```

**Comment by skeeler** [comment]
Just noticed the readme.md indicates target has to be TFS 2018 or VSTS, i.e. not TFS 2017 as I am using with the "api-version=3.0" setting to make the REST API call not fail. Perhaps there are functional limitations in the 3.0 version of the VSTS REST API that make it impossible to use the necessary functionality with versions of TFS earlier than 2018. Thoughts?

**Comment by Paulohcsantos** [comment]
Hi @skeeler ,   
I resolved this probleam apply a new version api 'Version-5.0-Preview'. 
Do you tryed this option?

**Comment by sferg-msft** [comment]
@skeeler Correct, the migrator only supports write operations to TFS 2018 or VSTS.

**Comment by jkc-NC** [comment]
@sferg-msft I got this exact same error but I am migrating from VSTS to VSTS, or more specifically, Devops as it is called now.
