### ISSUE TITLE
A video on how to use the tool

### ISSUE THREAD

**Issue by DevOpsFounder** [Microsoft/vsts-work-item-migrator#14]
I created a video on how to use the tool so anyone can get quickly overview of it, I thought to make a pull request to add it to the readme then I thought it's better to leave that to you if you think it could help.
Thanks!
https://www.youtube.com/watch?v=aHbiLYUfomc&feature=youtu.be

**Comment by Paulohcsantos** [comment]
Thanks for help, @DevOpsFounder

**Comment by DevOpsFounder** [comment]
No problem @Paulohcsantos

**Comment by sferg-msft** [comment]
Fixed with #59
