### ISSUE TITLE
The tool doesn't migrate the shared step in the steps

### ISSUE THREAD

**Issue by DevOpsFounder** [Microsoft/vsts-work-item-migrator#15]
While the tool migrate the linked shared steps to the test cases, it doesn't migrate it as a step in the steps for the test cases
![image](https://user-images.githubusercontent.com/14263956/38244929-246e13a0-3734-11e8-81b8-498e4182fa4f.png)

**Comment by sferg-msft** [comment]
Unfortunately shared steps are test artifacts, and the tool does not support migrating test data.
