### ISSUE TITLE
Migration fails when project name has spaces

### ISSUE THREAD

**Issue by matiaskusack** [Microsoft/vsts-work-item-migrator#24]
Hello, I've been trying to migrate a project that has spaces in its name. The error the migration tool was giving me was something like "Could not found area path for project ...".

The project had spaces in its name, and since the default area path is the project name, the only way of changeing it was by renaming the project.

So I did and it worked.

Regards

**Comment by Paulohcsantos** [comment]
You tried apply the word '%20' between the name?

**Comment by matiaskusack** [comment]
Hi, no I haven't. Next time I'll give it a try.


Thanks


Matías Kusack
________________________________
De: Paulohcsantos <notifications@github.com>
Enviado: viernes, 25 de mayo de 2018 13:41:03
Para: Microsoft/vsts-work-item-migrator
Cc: Matías Kusack; Author
Asunto: Re: [Microsoft/vsts-work-item-migrator] Migration fails when project name has spaces (#24)


You tried apply the word '%20' between the name?

**Comment by sferg-msft** [comment]
@matiaskusack Could you please attach the error log?  It is possible the area path mapping was incorrect.

**Comment by sferg-msft** [comment]
Closing due to no response from @matiaskusack
