### ISSUE TITLE
Migration fails at the end of phase 2, when applying tags.

### ISSUE THREAD

**Issue by francescoPizzolon** [Microsoft/vsts-work-item-migrator#27]
I'm migrating from TFS 2017 update 3.
Migration fails at the end of phase 2, when applying tags. It returns: Status Code: 404.
[WiMigrator_Migrate_2018-06-07_14-45-19.log](https://github.com/Microsoft/vsts-work-item-migrator/files/2084958/WiMigrator_Migrate_2018-06-07_14-45-19.log)
[WitBatchRequestsFromBatch4WithFailure2018-06-07_14-50-33-14.log](https://github.com/Microsoft/vsts-work-item-migrator/files/2084959/WitBatchRequestsFromBatch4WithFailure2018-06-07_14-50-33-14.log)
[WitBatchRequestsFromBatch3WithFailure2018-06-07_14-50-32-09.log](https://github.com/Microsoft/vsts-work-item-migrator/files/2084960/WitBatchRequestsFromBatch3WithFailure2018-06-07_14-50-32-09.log)
[WitBatchRequestsFromBatch2WithFailure2018-06-07_14-50-31-056.log](https://github.com/Microsoft/vsts-work-item-migrator/files/2084961/WitBatchRequestsFromBatch2WithFailure2018-06-07_14-50-31-056.log)
[WitBatchRequestsFromBatch1WithFailure2018-06-07_14-50-29-806.log](https://github.com/Microsoft/vsts-work-item-migrator/files/2084962/WitBatchRequestsFromBatch1WithFailure2018-06-07_14-50-29-806.log)

**Comment by sferg-msft** [comment]
@francescoPizzolon Sorry, this is because the migrator only supports writing to TFS 2018 or VSTS.  If you disable tagging on the source you should not see any errors.
