### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by aroyappan** [Microsoft/vsts-work-item-migrator#30]
I have some work items already in the target project and now I am trying to migrate the old work items. In this Validation went successfully but after executing the migrate command I am getting the following error message “An item with the same key has already been added.” I try to change the work item titles to be unique.I also try creating a new project and run the migration to the newly created project. But still same issue. Could you please help on this, what I am doing wrong.

**Comment by sferg-msft** [comment]
Closing due to no response.
