### ISSUE TITLE
Account Uri requires trailing '/'

### ISSUE THREAD

**Issue by tbergstedt** [Microsoft/vsts-work-item-migrator#31]
I encountered a problem when copying attachments in on-premises TFS. For every attachment that was to be copied, I received the following warning:
`[Warning   @15.22.59.449] Exception caught for b55743bd-e3a1-4663-84ee-d9c54534a5de:
System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'ExceptionResponse' from content with media type 'text/html'.
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at Common.WorkItemTrackingHelpers.<>c__DisplayClass11_0.<<CreateAttachmentChunkedAsync>b__0>d.MoveNext() in C:\repos\WiMigrator\Common\WorkItemTrackingHelpers.cs:line 138`

The problem was that the combined REST API address lacked a '/' between account Uri and '_apis/...', thus making the call to upload attachments failed. When this was noticed during debugging, it was a simple task to add the trailing '/' to make it work, but I believe this could be solved by either documenting it in sample-configuration.json, or -better - by automatically adding a trailing '/' if missing.

**Comment by sferg-msft** [comment]
I can fix this when I get back from my vacation.

**Comment by sferg-msft** [comment]
@jkc-NC Yep!  #57
