### ISSUE TITLE
failed for this reason: BadRequest

### ISSUE THREAD

**Issue by Tenseiga** [Microsoft/vsts-work-item-migrator#39]
Hi Team,

I am getting the issue BadRequest , when trying to migrate from VSTS to another VSTS. Validation is getting passed.

**Comment by timg83** [comment]
I also had this problem. I've set the log-level-for-file property to 'trace'. After you tried the migration you'll find a log file in the directory where you can find more information.

In my case there were some iteration paths missing in the target VSTS.

**Comment by sferg-msft** [comment]
@Tenseiga Is this still an issue?

**Comment by Tenseiga** [comment]
No kindly close the issue. Sorry forgot to close it.
