### ISSUE TITLE
Only the last history/discussion item moved over on a VSTS to TFS Migration  

### ISSUE THREAD

**Issue by higyigma** [Microsoft/vsts-work-item-migrator#42]
**Expected**:

![screenshot](https://user-images.githubusercontent.com/6162649/47437195-097b7a00-d776-11e8-9e45-9fe6b0be2374.png)
As you can see, there is a large discussion history on the original work item. When I run the tool, I expected it to copy all of these comments.

**Actual**:

![screenshot2](https://user-images.githubusercontent.com/6162649/47437483-b0f8ac80-d776-11e8-9a88-efaa3a03da44.png)
As you can see, the only item copied was the last one in the chain. I'm not sure if this is intentional or not, but I do think it's important if it copies over the history to copy over all of it.

**Comment by sferg-msft** [comment]
Yes, that is the current design.  The history of the work item is not replayed, just the latest revision.  Discussion comes from the history of the work item.  The contents of discussion should be included as an attachment with all the history if you included that option when migrating.
