### ISSUE TITLE
Discussion not migrating for VSTS to VSTS Migration

### ISSUE THREAD

**Issue by pauldmaddox** [Microsoft/vsts-work-item-migrator#44]
We are performing a VSTS-->VSTS Migration.
All source data appears to be migrating well except discussion which is always blank in the destination system.

**Comment by pelvark** [comment]
@pauldmaddox 
The question is old, but did you check the attachment? the discussion should be added as a file with history in attachment.

**Comment by sferg-msft** [comment]
Yes, discussion is actually the history of the work item.  That is not migrated except as part of the file @pelvark mentioned.
