### ISSUE TITLE
Please add support for remote links.

### ISSUE THREAD

**Issue by paulCullivan** [Microsoft/vsts-work-item-migrator#53]
Hey Sean, it would be great if the WiMigrator tool could support the new remote link type for ADO:

https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=azure-devops&tabs=browser#link-to-a-remote-work-item

https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops#remote-work-link-types

Thanks!  Appreciate the help and for making this tool.

**Comment by sferg-msft** [comment]
Makes perfect sense.  Since I don't think we actually want to create the remote links, I will migrate remote links as hyperlinks.

**Comment by sferg-msft** [comment]
This has been resolved with PR #56
