### ISSUE TITLE
Images in description field are not strictly copied, but linked to old

### ISSUE THREAD

**Issue by pelvark** [Microsoft/vsts-work-item-migrator#55]
I did a migration using the tool and thought everything went well in the end. 
After deleting the old project I found that all the images that were in the description field of the work items where gone. 

It seems the images in the target projects description was simply linking to the old projects images, so when it was deleted so were their sources. 

I realize the fault is my own for not realizing the images were simply linking back to their old ones. But it might be a neat enhancement if images in the description field were re-hosted in the new project.

**Comment by sferg-msft** [comment]
They should have been, could you let me know what version of TFS you were migrating from?

**Comment by sferg-msft** [comment]
@pelvark What version of TFS were you migration from?

**Comment by pelvark** [comment]
It was from VSTS to VSTS

**Comment by sferg-msft** [comment]
@pelvark Could you share an example URL?  There was an Azure DevOps bug that was recently fixed that had the URLs for inline attachments mismatched.

**Comment by sferg-msft** [comment]
Actually, I reprod myself.  Azure DevOps switched inline image formats, and the migrator was not updated to reflect that.  I'll get that fixed now.
