### ISSUE TITLE
Is it possible to Migrate work items from TFS 2010 to TFS 2018 or Latest?

### ISSUE THREAD

**Issue by gopireddyravindar** [microsoft/vsts-work-item-migrator#75]
Hello,

Can you please let me know if it possible to migrate work-items & it's flow to TFS 2018/2019?

Is there anyway to get this done? 
Thank you,
RR

**Comment by philspokas** [comment]
The API this app depends on is only supported in TFS 2015 and later. See https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops 
Further, the code specifies revision 4 of the api which means TFS 2018 is the minimum version.
You will need to upgrade TFS prior to migrating using this tool.
