### ISSUE TITLE
How update only area and iteration path

### ISSUE THREAD

**Issue by JULIANCHO923** [microsoft/vsts-work-item-migrator#78]
Hello, 
I migrated my work items but i forgot create in the target the correct iterations

Now, I created the correct iterations and **i want only update the area and iteration path**

How is possible do that?

This is my config

> {
  "source-connection": {
    "account": "https://source.visualstudio.com",
    "project": "projectSource",
    "access-token": "...................",
    "use-integrated-auth": "false"
  },
  "target-connection": {
    "account": "https://target.visualstudio.com",
    "project": "projectTarget",
    "access-token": "........................",
    "use-integrated-auth": "false"
  },
  "query": "My Queries/AllWorkItems",
  "heartbeat-frequency-in-seconds": 30,
  "query-page-size": 20000,
  "parallelism": 1,
  "max-attachment-size": 62914560,
  "link-parallelism": 1,
  "attachment-upload-chunk-size": 1048576,
  "skip-existing": false,
  "move-history": true,
  "move-history-limit": 200,
  "move-git-links": true,
  "move-attachments": true,
  "move-links": true,
  "skip-work-items-with-type-missing-fields": false,
  "skip-work-items-with-missing-area-path": false,
  "skip-work-items-with-missing-iteration-path": false,
  "clear-identity-display-names": false,
  "ensure-identities": false,
  "include-web-link": true
}

**Comment by JULIANCHO923** [comment]
Do you know something to do? @obvioussean  @devandanger @microsoftopensource @msftgits @valenker @julioarruda @iwhp

**Comment by obvioussean** [comment]
You have two options:
- Delete all the work items and start again
- Edit all the source work items so that the migrator will pick them up and migrate the area/iteration path changes
